name: Lint Code Base

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          ACTIONS_RUNNER_DEBUG: true
          DEFAULT_BRANCH: $default-branch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_EDITORCONFIG: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_YAML: true
